"""Configurações do renderer WhatsApp."""

# ── FFmpeg ──
FFMPEG_CRF = 18
FFMPEG_PRESET = "ultrafast"
FFMPEG_AUDIO_BITRATE = "192k"

# ── Animação ──
MIN_MESSAGE_DELAY = 800
MAX_MESSAGE_DELAY = 2500
TYPING_INDICATOR_MIN = 500
TYPING_INDICATOR_MAX = 1500
SCROLL_DURATION_MIN = 300
SCROLL_DURATION_MAX = 600
IMAGE_PAUSE_MIN = 1500
IMAGE_PAUSE_MAX = 3000
MICRO_PAUSE_MIN = 200
MICRO_PAUSE_MAX = 500

# ── Variação humana ──
HUMAN_VARIATION_PERCENT = 0.20  # ±20%

# ── Cores WhatsApp ──
WHATSAPP_HEADER_COLOR = "#075e54"
WHATSAPP_SENT_COLOR = "#dcf8c6"
WHATSAPP_RECEIVED_COLOR = "#ffffff"
WHATSAPP_BG_COLOR = "#e5ddd5"
